#! /bin/bash

# This displays battery percent and a corresponding bitmap icon at different levels of its percentage.

batperc=$(acpi -b | sed -n "1p" | awk -F " " '{print $4}' | head -c3)
batpercint=$(acpi -b | sed -n "1p" | awk -F "[% ]" '{print $4}' | head -c3)
batstatus=$(acpi -b | sed -n "1p" | awk -F "[, ]" '{print $3}')
default='#707070'
bold='#adadad'
highlight='#FF96A3'

if [ "$batstatus" == "Charging" ]; then
    echo "^fg($default)⮒ ^fg($bold)$batstatus ^fg($default)$batperc"
elif [ $batpercint -lt 20 ]; then
    echo "^fg($highlight)⮐ $batstatus $batperc"
elif [ $batpercint -lt 50 ]; then
    echo "^fg($default)⮑ ^fg($bold)$batstatus ^fg($default)$batperc"
# The next elif is a workaround for when acpi outputs 'Unknown, 99%' when it really means charged full at 100%.
# This is likely due to some hardware problem (laptop, surge protector, or otherwise). Too lazy to fix.
elif [ "$batstatus" == "Unknown" ] && [ $batpercint -eq 99 ]; then
    echo "^fg($default)⮎ 100%"
elif [ $batstatus == "Discharging" ]; then
    echo "^fg($default)⮏ ^fg($bold)$batstatus ^fg($default)$batpercint%"
else
    echo "^fg($default)⮎ $batperc%"
fi
