#! /bin/bash

# As my mail notification system, this displays unread mail count if it's greater than
# zero. The unread mail count is given by my two gmail scripts, each of which monitor
# a different account.

#gmail1=$(python ~/.config/nil/conky/scripts/gmail1.py)
#gmail2=$(python ~/.config/nil/conky/scripts/gmail2.py)
gmail1='a'
gmail2='a'
icon='/home/nil/.config/nil/conky/xbm/mail.xbm'
highlight='#FF96A3'

#if [ ( $gmail1 -gt 0 ) || ( $gmail2 -gt 0 ) ]; then
#echo "^fg($highlight)^i($icon) ${execp python ~/.config/nil/conky/scripts/gmail1.py}${execp python ~/.config/nil/conky/scripts/gmail2.py}  "
#fi

#Test this first
#if [ $gmail1 -gt 0 ]; then
if [ 0 -gt 0 ]; then
#if [ "`python ~/.config/nil/conky/scripts/gmail1.py`" -gt 0 ]; then
echo "^fg($highlight)success!  "
#echo "^fg($highlight)^i($icon) $gmail1$gmail2  "
fi
