#! /bin/bash

# This displays mpd now playing info if mpd is running, and if play or pause.

so=`mpc current -f %title%`
art=`mpc current -f %artist%`
default='#707070'
bold='#adadad'

#line=$(mpc current)

#if [ -n "$line" ] && [ "`mpc | grep "^\[paused\]"`" != "" ]; then
if [ "`mpc | grep "^\[paused\]"`" != "" ]; then
    echo -n "^fg($default)⮕ ^fg($bold)Paused: ^fg($default)$so ^fg($bold)by ^fg($default)$art"
    else
    echo -n "^fg($default)⮕ ^fg($bold)Playing: ^fg($default)$so ^fg($bold)by ^fg($default)$art"
fi
