#! /bin/bash

# This displays mpd now playing info if mpd is running, and if play or pause.

so=`mpc current -f %title%`
art=`mpc current -f %artist%`
icon='/home/nil/.config/nil/conky/dzen2/note.xbm'
default='#707070'
bold='#adadad'

if [ "`mpc | grep "^\[paused\]"`" != "" ]; then
    echo -n "^i($icon) ^fg($bold)Paused: ^fg($default)$so ^fg($bold)by ^fg($default)$art"
    else
    echo -n "^i($icon) ^fg($bold)Playing: ^fg($default)$so ^fg($bold)by ^fg($default)$art"
fi
