#! /bin/bash

# Pgrep PID.
pgrep mpv
# If not running.
if [ $? -ne 0 ]
then
    ncmpcpp toggle &
else
# Else (if it is running)
    echo "cycle pause" > ~/.config/nil/mpv-control
# This one will always allow to pause ncmpcpp, e.g., I open mpv while ncmpcpp is playing.
    ncmpcpp pause
fi
